// <auto-generated />
namespace _2013215462_PER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ADD : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ADD));
        
        string IMigrationMetadata.Id
        {
            get { return "201705140609079_ADD"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
